# Generated by Django 4.0a1 on 2021-10-15 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20211011_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=128)),
                ('contact_info', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('pay_period', models.IntegerField(choices=[('', 'Select Pay Period'), (1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Per Job')])),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ot_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('camera_ot_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extras', models.DecimalField(decimal_places=2, max_digits=10)),
                ('working_hours', models.IntegerField(choices=[('', 'Select Working Hours'), (1, '10hr Continuous Day'), (2, '11hr Day'), (3, '12hr Day')])),
                ('description', models.CharField(max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512, null=True)),
                ('crew_members', models.ManyToManyField(to='work_logger.CrewMember')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_logger.project')),
                ('terms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_logger.terms')),
            ],
        ),
        migrations.CreateModel(
            name='ShootingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=512, null=True)),
                ('start_hour', models.DateTimeField()),
                ('end_hour', models.DateTimeField()),
                ('ot', models.IntegerField()),
                ('camera_ot', models.IntegerField()),
                ('toc', models.IntegerField()),
                ('extras', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_logger.subproject')),
            ],
        ),
    ]
